### ISSUE TITLE
Stop on broken promise

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#41]
Stuff like
```
(node:2114) UnhandledPromiseRejectionWarning: Error: Requested rebar3 version (from spec 3.6.1) not found in build listing
    at getRebar3Version (/home/runner/work/_actions/erlef/setup-beam/v1/dist/index.js:4803:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async maybeInstallRebar3 (/home/runner/work/_actions/erlef/setup-beam/v1/dist/index.js:4716:27)
````
(test with an inexisting `rebar3` version, for example)
should stop the build process in that step, but the exception is somehow being ignored.

**Comment by paulo-ferraz-oliveira** [comment]
This is not possible to replicate in a more recent version of the action. Closing.
